package:
  name: metautils
  version: 0.1.2

source:
  git_url: ../

requirements:
  build:
    - python x.x
    - setuptools
  run:
    - python x.x
    - functools32  # [py27]

test:
  requires:
    - nose ==1.3.7
  imports:
    - metautils
  commands:
    - nosetests metautils

about:
  home: https://github.com/quantopian/metautils
  license: Apache Software License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
